name: zookeeper container example
on: push

jobs:
  # Label of the container job
  container-job-zookeeper:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ubuntu

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      zookeeper:
        # Docker Hub image
        image: confluentinc/cp-zookeeper:7.2.0
        env:
           ZOOKEEPER_CLIENT_PORT: 2181
           KAFKA_OPTS: "-Dzookeeper.admin.enableServer=false"
        # Set health checks to wait until redis has started

      kafka:
        image: confluentinc/cp-kafka:7.2.0
        env:
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Test Zookeeper
          run: |
            #apk add wget
            apt-get update
            apt-get install -y wget default-jre
            wget https://dlcdn.apache.org/zookeeper/zookeeper-3.8.3/apache-zookeeper-3.8.3-bin.tar.gz
            tar -zxvf apache-zookeeper-3.8.3-bin.tar.gz
            ./apache-zookeeper-3.8.3-bin/bin/zkCli.sh -server zookeeper:2181

        - name: Test kafka
          run: |
             apt-get update
             apt-get install -y python3  python3-pip
             pip3 install confluent_kafka
             python3 kafka-connect.py         
