name: mysql container example
on: push

jobs:
  # Label of the container job
  container-job-zookeeper:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ubuntu

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image
        image: mysql:5.7
        env:
           MYSQL_ROOT_PASSWORD: "test"
           MYSQL_DATABASE: ""
           MYSQL_USER: "test"
           MYSQL_PASSWORD: "test"
        # Set health checks to wait until redis has started
        options: --log-bin-trust-function-creators=0

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install wget and test
        run: |
             apt-get update
             apt-get install -y python3  python3-pip
             pip3 install mysql-connector-python
             python3 mysql-connector.py       
