name: Opa container example
on: push

jobs:
  container-job-opa:
    runs-on: ubuntu-latest
    container: ubuntu

    services:
      opa:
          image: jasmitha/opa:0.20.5-debug

    steps:
        - name: Install curl
          run: |
            apt-get update
            apt-get install -y curl
            curl -i opa:8181/v1/data 
