name: Redis container example
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
            echo "123"
