name: Caching

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: maven

    steps:
    - uses: actions/checkout@v3

    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: maven version
      run: mvn -v

    - name: maven version
      run: mvn compile

    - name: maven version
      run: mvn install
