name: zookeeper container example
on: push

jobs:
  # Label of the container job
  container-job-zookeeper:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: ubuntu

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      zookeeper:
        # Docker Hub image
        image: confluentinc/cp-zookeeper:7.2.0
        env:
           ZOOKEEPER_CLIENT_PORT: 2181
           KAFKA_OPTS: "-Dzookeeper.admin.enableServer=false"
        # Set health checks to wait until redis has started

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      #- name: Check out repository code
      #  uses: actions/checkout@v3

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      #- name: Install dependencies
      #  run: npm ci

        - name: Install curl
          run: |
            wget https://www.apache.org/dyn/closer.lua/zookeeper/zookeeper-3.8.3/apache-zookeeper-3.8.3-bin.tar.gz
            tar -zxvf apache-zookeeper-3.8.3-bin.tar.gz
            ./apache-zookeeper-3.8.3-bin/bin/zkCli.sh -server zookeeper:2181
