name: Opa container example
on: push

jobs:
  container-job-opa:
    runs-on: ubuntu-latest
    container: ubuntu

    services:
      opa:
          image: openpolicyagent/opa:0.20.5-debug
          options: |
|           --name opa-container
            --server
            --log-level debug

    steps:
        - name: Install curl
          run: |
            apt-get update
            apt-get install -y curl
            sleep 60
            curl -i opa:8181
