name: Schedule workflow
on:
   schedule:
     - cron: '*/15 * * * *'

jobs:
   test_schedule:
     runs-on: ubuntu-latest
     steps:
       - name: Every time
         run: |
           echo "${{ github.triggering_actor }}"
           echo "${{ github.actor }}"
