name: Schedule workflow
on:
   schedule:
     - cron: '*/6 * * * *'

jobs:
   test_schedule:
     runs-on: ubuntu-latest
     steps:
       - name: Every time
         run: |
           echo "${{ github.triggering_actor }}"
           echo "${{ github.actor }}"
           echo "${{ github.event.schedule }}"
       - name: schedule time
         if: github.event.schedule == ''
         run: |
           echo "works"
           
