name: Redis container example
on: push

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: branch 
        run: |
           git branch

