name: Redis container example
on: push

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    env:
      image_env: ''
    container:
      image: ubuntu
    services:
      test:
        image: $image_env
    steps:
      - name: Command
        run: |
         pwd
         echo ${{ github.workspace }}
         echo 1234

