name: Redis container example
on: 
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
            if [[ ${{ github.ref_name }} =~ .*dev-usw2 ]]; then
              echo "dev-usw2"
            elif [[ ${{ github.ref_name }} =~ .*perf-usw2 ]]; then
              echo "perf-usw2"
            elif [[ ${{ github.ref_name }} =~ .*perf-euc1 ]]; then
              echo "perf-euc1"
            else
              echo "Tag is unset or empty. This will not be deployed to any environment."
            fi
