name: Redis container example
on: 
  pull_request:
     types: [opened, synchronize, reopened]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: branch 
        run: |
           git branch

