name: Redis container example
on: push

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - name: Command
	env:
	  GHA_PATH: '${{ github.workspace }}'
        run: |
         pwd
         echo $GHA_PATH
         echo 1234

