name: Redis container example
on: push

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    services:
      test:
        image: ubuntu 
    steps:
      - name: Command
        run: |
         pwd
         echo ${{ github.workspace }}
         echo 1234

