name: Redis container example
on: push

jobs:
  container-test-job:
    env:
      image_env: ''
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    services:
      test:
        image: ${{ env.image_env }}
    steps:
      - name: Command
        run: |
         pwd
         echo ${{ github.workspace }}
         echo 1234

