name: Workflow
on:
  workflow_dispatch:
    inputs:
      parameters:
        description: 'Parameters for the workflow'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy using Terraform
        run: |
           echo ${{ fromJson(github.event.inputs.parameters).project }} 
           echo ${{ fromJson(github.event.inputs.parameters).organization_name }} 
