name: Workflow
on:
  workflow_dispatch:
    inputs:
      parameters:
        description: 'Parameters for the workflow'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
           keys=$(echo '${{ inputs.parameters }}' | jq -r 'keys_unsorted[]')
           echo $keys
           for key in $keys; do
              value=$(echo '${{ inputs.parameters }}' | jq -r ".$key")
              echo "${key}=${value}" >> "${GITHUB_ENV}"
           done

           echo $a1  
       # echo "${{ fromJson(inputs.parameters).a1 }}"
       # echo "${{ fromJson(inputs.parameters).a2 }}"
       # echo "${{ fromJson(inputs.parameters).a3 }}"
       # echo "${{ fromJson(inputs.parameters).a4 }}"
       # echo "${{ fromJson(inputs.parameters).a5 }}"
       # echo "${{ fromJson(inputs.parameters).a6 }}"
       # echo "${{ fromJson(inputs.parameters).a7 }}"
       # echo "${{ fromJson(inputs.parameters).a8 }}"
       # echo "${{ fromJson(inputs.parameters).a9 }}"
       # echo "${{ fromJson(inputs.parameters).a10 }}"
       # echo "${{ fromJson(inputs.parameters).a11 }}"
       # echo "${{ fromJson(inputs.parameters).a12 }}"
       # echo "${{ fromJson(inputs.parameters).a13 }}"
       # echo "${{ fromJson(inputs.parameters).a14 }}"

